### ISSUE TITLE
Problem with code generation of Channel struct

### ISSUE THREAD

**Issue by gerritsangel** [CleverCloud/lapin#282]
Hello,

It seems that the Channel struct is almost completely code generated based on `lapin.json`.
I wonder if this could be somehow improved, mainly because of two problems which at least I have:

-  I'm using the Rust plugin for CLion which unfortunately fails recognizing the generated code. It has a macro expansion engine, but as it is not a macro, it cannot recognize the generated methods and does not offer any auto completion. This is quite problematic as Channel is more or less the entry point to everything and this makes debugging quite hard.

- It's hard to write some documentation about the individual methods.

For the first part, I wonder if a procedural macro which expands the JSON wouldn't be nicer? Sure, CLion is only one specific IDE, but the tooling becomes nicer and nicer and it would be great if it could work.

The second part could be improved by just changing the template a bit, I guess.

Thanks for the great work on the crate!

**Comment by Keruspe** [comment]
Hi,

wrt the second point, I just published a PoC of how it could be handled in commit cee3222eef20598f5bbf70b741c63092cd3d9b6b

**Comment by gerritsangel** [comment]
Thanks, I will use that to write some docs :)

**Comment by JamesGuthrie** [comment]
I would like to add that I am using IntelliJ with the Rust plugin and I've had similar issues. I found it very difficult to explore the API because there is seemingly neither documentation of which methods are available, nor is there source code which I can browse for a bunch of methods. For instance the methods `basic_publish`, `queue_declare`, `basic_consume` on the Channel are just not present in the source code anywhere. The only accessible "documentation" that I can find are the examples.

Am I missing something here?

**Comment by Keruspe** [comment]
cargo doc and/or docs.rs?

**Comment by Keruspe** [comment]
Codegen is now optional in 1.1.0

**Comment by gerritsangel** [comment]
I just wanted to add that imho the “problem” here is just the different workflow with an IDE and without an IDE. I guess if you develop with VIM or another text editor, you check for the available documentation on docs.rs first.
If you are used to an IDE, the workflow is more like “Let me press `.` on a struct and see which methods are available there”.

For example, working with Java in IntelliJ just makes fun because you almost never have to work through the Javadocs.
