### ISSUE TITLE
How to use lapin on multi thread cnotext ? 

### ISSUE THREAD

**Issue by emacsist** [CleverCloud/lapin#294]
any examples ? thanks

**Comment by Keruspe** [comment]
Nothing specific to do here, do you have an example of what you’re trying to do?

**Comment by emacsist** [comment]
> Nothing specific to do here, do you have an example of what you’re trying to do?

e.g. Use lapin with [warp](https://github.com/seanmonstar/warp) to handle request , and publish message ?

**Comment by Keruspe** [comment]
As long as there’s a way to share some state, you just need to carry a Channel in this state and use it

**Comment by emacsist** [comment]
Thanks,  I'll try it out

**Comment by emacsist** [comment]
I still don't know how to use it with warp .  Hope there are some examples for web env. thanks. 

warp filter can not use async function, and the lapin create channel is async .

**Comment by Keruspe** [comment]
So the problem here is not about multithread, it's about non-async context.

First, you can create a channel before starting warp, and share it everywhere (Channel implement Clone) if that can simplify things.
Then, as opposed to most futures, the futures created by lapin run in the background even when not polled, polling / await it only here to wait for completion and/or error.
I suggest you to just spawn you AMQP stuff inside the tokio executor, which will be able to run async/await code, and if you need blocking behaviour, you can create a channel, pass the sender to the future inside the tokio-executor and just use recv on the receiver, which will block until the executor is done running the future

**Comment by emacsist** [comment]
Oh, I test ok. thanks very very much.
