### ISSUE TITLE
lapin::Queue::message_count() return the count not correct

### ISSUE THREAD

**Issue by Uchiha007** [CleverCloud/lapin#344]
I set prefetch_count to a big value, then call the message_count and get 0

**Comment by Uchiha007** [comment]
I want to get the message count that has not been consumed. For example, when I put 10 message to the queue, then I start the consumer server, call the `message_count` fn, the message count is 0.

**Comment by Keruspe** [comment]
I see where the confusion is. Declaring a queue as defined by AMQP specifications returns information such as the message count *at the moment when the server replied to the queue declaration*.
If you want up to date information you have two possibilities: either declare again the queue and get the message count in the response or use basic_get instead of basic_consume: it returns a single message, with metadata such as the message count after poping that message

**Comment by Uchiha007** [comment]
I tried to redeclare the queue again, but the message count not correct. Atually I just want to get multi messages at once.

**Comment by Keruspe** [comment]
I cannot reproduce your problem here, can you provide an example project reproducing the problem?

**Comment by Uchiha007** [comment]
Example, I have  100 messages in the queue.
`
channel.basic_qos(50, ..);
let consumer = channel.basic_consume(..);
let queue  = channel.queue_declare(..);
let cnt = queue.message_count(..); // 50
`
Anyway, I use basic_get instead of basic_consume solve the problem.
Thanks very much!

**Comment by Keruspe** [comment]
Does it return 50?
That's what I would expect. If you publish 100 messages, then create a consumer with 50 prefetch messages, you end up with 50 messages in your consumer waiting to be used and 50 in your queue waiting to be consumed (which is what queue_declare returns)

**Comment by Uchiha007** [comment]
Yes, you are right. But I never know the exactly number in my queue in some case (if there are 30 messages in all).
